spring.datasource.url=jdbc:mariadb://localhost:3307/LoveCode
spring.datasource.username=db_admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=8080
spring.jpa.properties.hibernate.globally_quoted_identifiers=true